services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"

  # Production app container (for deployment)
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app:ro
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/todoapp
    depends_on:
      - mongodb